### ISSUE TITLE
Can no longer view a date range

### ISSUE THREAD

**Issue by theres-waldo** [globau/logbot#41]
Previously (when the logs were at http://logs.glob.uno), you could view logs for a channel for a range of dates, I think up to 28 days or so.

Now that the logs are at https://mozilla.logbot.info/, that ability seems to be gone - you can only view one day at a time.

I found viewing multiple days at a time to be very useful. Please consider bringing that feature back.

**Comment by globau** [comment]
what's your use-case here?

i'm not keen on implementing the same multi-date experience as the previous version; i have concerns from both UX and technical perspectives.  the previous implementation jumped through quite a few hoops so it could avoid building an entire template in memory; the new version uses a dramatically simpler pipeline for building responses, and also runs on a server with significantly fewer resources.

would the ability to load the previous/next date's logs via xhr satisfy your needs?  something like "infinite scroll", only triggered by a click rather than scrolling.

**Comment by globau** [comment]
I've had a few attempts at this but it introduces a lot more complexity than I'm comfortable with.
