### ISSUE TITLE
ability to link to a message

### ISSUE THREAD

**Issue by hotsphink** [globau/logbot#70]
Given a timestamp (to within a few seconds), a channel, and a nick, I would like to be able to link to the message sent by that nick, at that time, to that channel.

Example: http://logs.glob.uno/?a=link_to&c=#jsapi&n=arai&t=1538472453 or something similar would redirect to https://mozilla.logbot.info/jsapi/20181002#c15400473 -- or it would, if that timestamp were correct, but it may not be (I approximated).

Thanks!

**Comment by globau** [comment]
notes for self:

- the old code is at https://github.com/globau/logbot/blob/version2/www/index.cgi#L698
- route could be something like `/#channel/link/:time/:nick`
- 302 instead of returning json

**Comment by globau** [comment]
fixed by 22bdf64 - route is as per my previous comment.
eg.  https://mozilla.logbot.info/jsapi/link/1538447278/arai

the channel, nick, and time are matched +/- 5 seconds, selecting the closest match by time.

the two most important results are `302` found and redirection, and `404` not found (missing channel or entry.
