### ISSUE TITLE
Message filter

### ISSUE THREAD

**Issue by dimir** [globau/logbot#82]
As I understood there's no such feature.
Would it be possible to implement a way for a user to notify that he doesn't want his message to be logged? E. g.

`<dimir> [nolog] This is a secret.`

**Comment by globau** [comment]
logbot is all or nothing – all messages sent in a public channel with logging enabled are public.

Rather than inventing a bespoke phrase as an indicator for logbot it would be better to use non-public channels for non-public messages.  This ensures the message will not be logged by logbot or any other bots/people in the public channel.

**Comment by dimir** [comment]
OK. In case you didn't know I'll just add a note here that FreeNode (where logbot service is offered) policy advises to offer such a way for a user:

https://freenode.net/policies

**Comment by globau** [comment]
https://freenode.net/policies
> consider providing a way for users to make comments without logging.

consider, not require.

**Comment by dimir** [comment]
Exactly.
